//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueprintMediaServis.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Contact
    {
        public int id { get; set; }
        public string slug { get; set; }
        public string statu_tr { get; set; }
        public string name_tr { get; set; }
        [AllowHtml]
        public string adress_tr { get; set; }
        public string phone_tr { get; set; }
        public string fax_tr { get; set; }
        public string mail_tr { get; set; }
        public string city_tr { get; set; }
        public string country_tr { get; set; }
        public string statu_en { get; set; }
        public string name_en { get; set; }
        [AllowHtml]
        public string adress_en { get; set; }
        public string phone_en { get; set; }
        public string fax_en { get; set; }
        public string mail_en { get; set; }
        public string city_en { get; set; }
        public string country_en { get; set; }
        public string statu_ru { get; set; }
        public string name_ru { get; set; }
        [AllowHtml]
        public string adress_ru { get; set; }
        public string phone_ru { get; set; }
        public string fax_ru { get; set; }
        public string mail_ru { get; set; }
        public string city_ru { get; set; }
        public string country_ru { get; set; }
    }
}
