//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueprintMediaServis.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public partial class MagazineCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MagazineCategory()
        {
            this.MagazinesContent = new HashSet<MagazinesContent>();
        }

        public int id { get; set; }
        public string text { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MagazinesContent> MagazinesContent { get; set; }

        public IEnumerable<SelectListItem> RetrieveMagazineCategory()
        {

            BlueprintMediaServisEntity BMSentity = new BlueprintMediaServisEntity();
            IEnumerable<SelectListItem> enumarableMagazineCategoryList;
            List<SelectListItem> magazineCategoryList = new List<SelectListItem>();

            foreach (MagazineCategory magazineCategory in BMSentity.MagazineCategory.ToList())
            {
                SelectListItem magazineCategoryItem = new SelectListItem() { Text = magazineCategory.text, Value = magazineCategory.id.ToString() };
                magazineCategoryList.Add(magazineCategoryItem);
            }
            enumarableMagazineCategoryList = magazineCategoryList;

            return enumarableMagazineCategoryList;
        }

        public List<MagazineCategory> RetriveMagazineCategory4API()
        {
            BlueprintMediaServisEntity db = new BlueprintMediaServisEntity();
            List<MagazineCategory> magazineCategoryList = new List<MagazineCategory>();
            MagazineCategory magazineCategoryTemp;

            foreach (MagazineCategory magazineCategoryItem in db.MagazineCategory)
            {
                magazineCategoryTemp = new MagazineCategory();
                magazineCategoryTemp.id = magazineCategoryItem.id;
                magazineCategoryTemp.text = magazineCategoryItem.text;


                magazineCategoryList.Add(magazineCategoryTemp);
            }

            //queryableMagazineCategoryList = (IQueryable<MagazineCategory>)magazineCategoryList;
            return magazineCategoryList;

        }

    }
}
