//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueprintMediaServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        public int id { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string pdfName { get; set; }
        public string imageName { get; set; }
        public string title { get; set; }
        public byte[] pdfFile { get; set; }
        public byte[] imageFile { get; set; }
    }
}
