//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueprintMediaServis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueprintMediaServisEntity : DbContext
    {
        public BlueprintMediaServisEntity()
            : base("name=BlueprintMediaServisEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalog> Catalog { get; set; }
        public virtual DbSet<Magazines> Magazines { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<MagazinesContent> MagazinesContent { get; set; }
    }
}
