//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueprintMediaServis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int id { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string embedcode_tr { get; set; }
        public string url_tr { get; set; }
        public string embedcode_en { get; set; }
        public string url_en { get; set; }
        public string embedcode_ru { get; set; }
        public string url_ru { get; set; }
    }
}
